server:
  port: ${PORT:8080}
app:
  version: "@project.version@"
spring:
  profiles:
    active:
#    - personal
    - release
  mustache:
    check-template-location: false
# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,jp.co.bzc.hashrize.vd
config:
  application-config-meta:
    version: "@project.version@"
logging:
  pattern:
    console: "%date [%thread] %-5level %logger - %msg%n"
  level:
    org:
      atmosphere: warn